version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
